---
title: "p8105_hw5_xz3078"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
```

## Problem 1

```{r message = FALSE}
homicide_df = 
  read_csv("./homicide-data.csv", na = c("", "Unknown")) %>%
  mutate(
    city_state = str_c(city, state),
    resolution = case_when(
      disposition == "Closed without arrest" ~ "unsolved", 
      disposition == "Open/No arrest" ~ "unsolved",
      disposition == "Closed by arrest" ~ "solved"
    )
  ) %>%
  relocate(city_state) %>%
  filter(city_state != "TulsaAL")
```

```{r}
baltimore_df = 
  homicide_df %>%
  filter(city_state == "BaltimoreMD")

baltimore_summary = 
  baltimore_df %>%
  summarize(
    unsolved = sum(resolution == "unsolved"),
    n = n()
  )

baltimore_test = 
  prop.test(
    x = baltimore_summary %>% pull(unsolved),
    n = baltimore_summary %>% pull(n)
  )

baltimore_test %>%
  broom::tidy()
```


```{r}
results_df = homicide_df %>%
  group_by(city_state) %>%
  summarize(
    unsolved = sum(resolution == "unsolved"),
    n = n()
  ) %>%
  mutate(
    test_results = map2(unsolved, n, prop.test),
    tidy_results = map(test_results, broom::tidy)
  ) %>%
  select(city_state, tidy_results) %>%
  unnest(tidy_results) %>%
  select(city_state, estimate, starts_with("conf"))

results_df
```

```{r}
results_df %>%
  mutate(city_state = fct_reorder(city_state, estimate)) %>%
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```


## Problem 2

```{r}
file_name = tibble(files = list.files("./data/"))

read_file_f = function(x) {
  read.csv(file = str_c("./data/", x))
}

file = list.files("./data/")
output = map(file, read_file_f)

values = output %>% 
  bind_rows()

data = tibble(file_name, values) %>% 
  separate(files, into = c("arm", "id"), sep = "\\_") %>%
  mutate(id = str_replace(id, "\\.csv", "")) %>%
  pivot_longer(
    week_1:week_8,
    names_to = "week", 
    values_to = "observation"
  ) %>%
  mutate(arm_id = str_c(arm, id)) %>%
  select(arm_id, everything())

data

data %>% 
  ggplot(aes(x = week, y = observation, group = arm_id, color = arm)) + 
    geom_line() + 
    labs(title = "“spaghetti” plot of observations on each subject over time")
```

We can see from the plot that experiment groups seem to have higher growth in observations over 8 weeks than control groups. There are not much changes in control groups over time. At week 7 and week 8, the observations of all experiment groups are higher than control groups. 

## Problem 3

```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species)) %>%
  janitor::clean_names()
```

```{r}
replace_missing = function(x) {
  
  if(is.numeric(x)) {
    x = ifelse(is.na(x), mean(x, na.rm = TRUE), x)
  }
  
  if(is.character(x)) {
     x = ifelse(is.na(x), "virginica", x)
  }
  
  return(x)
  
}

map_df(iris_with_missing, replace_missing)
```




